### ISSUE TITLE
Support for Nested Schemas

### ISSUE THREAD

**Issue by nhitchins** [mongoosejs/mongoose-double#1]
does not seem to type-cast attributes on nested schema's (same for mongoose-long).
example:

myNestedSchema = new mongoose.Schema { dbl: mongoose.Schema.Types.Double }
myMainSchema = new mongoose.Schema { arr: [myNestedSchema] }

**Comment by aheckmann** [comment]
works for me. can you provide more information? mongoose version, nodejs version?

**Comment by nhitchins** [comment]
Hi Aaron, 
Its probably me, but i'm having issues with even simple type-casting using mongoose-double, whereas mongoose-long works as expected. 

Dev environment: Win8x64 Node ver 0.10.13, mongoose 3.6.14, mongodb 2.4.5

Can you take a quick look at this basic example and let me know what i'm doing wrong....when I view the document attribute types in the database, the long attr is an int64 but the double attr is a string "123.12"

var mongoose = require("mongoose");
require("mongoose-double")(mongoose);
require("mongoose-long")(mongoose);

mongoose.connect("mongodb://localhost:27017/local");

var TestSchema = new mongoose.Schema({
  double : mongoose.Schema.Types.Double,
  long : mongoose.Schema.Types.Long
});

Test = mongoose.model("Test", TestSchema, "test");
var test = new Test({double: "123.12", long: "123.12"});

test.save(function(err){
  console.log("saved: ", test.double, err);
});

**Comment by nhitchins** [comment]
Any updates on this? 
Just does not seem like the underlying mongodb driver is respecting the bson double type on insertion into the DB. I've also tried across a few different mongoose/mongodb versions with no success. inspection of the datatype in the saved document always shows the double being saved as whatever type the value was passed in as...ie. string/int.

**Comment by nhitchins** [comment]
still doesnt work. have you tested this and checked the actual datatype in the db is double?

**Comment by aheckmann** [comment]
this project has taken a very low priority for me recently. I'll take a PR that includes tests.
