### ISSUE TITLE
required and default

### ISSUE THREAD

**Issue by akoskm** [mongoosejs/mongoose-double#2]
Should this plugin support the `default`  options from mongoose? Looks like `required` is supported https://github.com/aheckmann/mongoose-double/blob/master/test/index.js#L143
but I don't see any tests for `default`.

**Comment by jitendrapawar** [comment]
just use `type : Double, default : 0` in your schema it works well

**Comment by akoskm** [comment]
Yes, I figured that out and created a test to prove it #3 . Looks like I forgot to close this issue.
